### ISSUE TITLE
[Bug]: iptables: Failed to initialize nft: Protocol not supported

### ISSUE THREAD

**Issue by arky** [RaspAP/raspap-webgui#1582] opened 2024-05-09 13:33 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Issue reporting checklist

- [X] I have read and understand the [issue reporting policy](https://docs.raspap.com/issues/).
- [X] I observed this bug on a clean install of a [supported OS](https://docs.raspap.com/#compatible-operating-systems).
- [X] I have followed the [project prerequisites](https://docs.raspap.com/#quick-start).
- [X] I have searched this repository for existing issues.
- [X] I checked the [FAQ](https://docs.raspap.com/faq/) and [official documentation](https://docs.raspap.com/).
- [X] I am using an [external wireless adapter](https://docs.raspap.com/issues/#external-hardware).
- [X] I have generated a [RaspAP debug log](https://docs.raspap.com/ap-basics/#debug-log) and performed a [self-diagnosis](https://docs.raspap.com/ap-basics/#diagnosing-problems).

### Operating System

Raspberry Pi OS	(64-bit) Lite Bookworm

### Quick install or Manual setup?

Quick install

### Onboard wireless chipset or external adapter?

Onboard wireless chipset

### Hardware

Raspberry Pi 3 Model B+

### RaspAP version

3.1.3 (Latest)

### Other software or services running with RaspAP?

Yes (specify below)

### Bug description

Debian has moved to used NFtables. During installation you'll get following errors related to iptables. 

``` 
Unable to execute iptables 
    /usr/bin/grep: /etc/iptables/rules.v4: No such file or directory
    Adding rule: -t nat -A POSTROUTING -s 192.168.50.0/24 ! -d 192.168.50.0/24 -j MASQUERADE

 Unable to execute iptables 
Persisting IP tables rules
 sudo: unable to resolve host arky-thinkpad: Name or service not known
 sudo: unable to resolve host arky-thinkpad: Name or service not known
 iptables-save/1.8.9 (nf_tables) Failed to initialize nft: Protocol not supported
 Unable to execute iptables-save 

```

### Steps to reproduce

Run the install on latest [Raspberry Pi OS image ](https://downloads.raspberrypi.com/raspios_lite_armhf/images/raspios_lite_armhf-2024-03-15/2024-03-15-raspios-bookworm-armhf-lite.img.xz) 
`curl -sL https://install.raspap.com | sudo bash -s -- --yes --openvpn 0 --adblock 0 --branch 2.9.8`

### Screenshots

-

### Additional context

https://gitlab.com/likebutter/butterbox-rpi/-/issues/73

### Relevant log output

```shell
Unable to execute iptables 
    /usr/bin/grep: /etc/iptables/rules.v4: No such file or directory
    Adding rule: -t nat -A POSTROUTING -s 192.168.50.0/24 ! -d 192.168.50.0/24 -j MASQUERADE

 Unable to execute iptables 
Persisting IP tables rules
 sudo: unable to resolve host arky-thinkpad: Name or service not known
 sudo: unable to resolve host arky-thinkpad: Name or service not known
 iptables-save/1.8.9 (nf_tables) Failed to initialize nft: Protocol not supported
 Unable to execute iptables-save 

```
```

**Comment by billz** [comment] 2024-05-09 16:27
Duplicate of #1513 See also https://github.com/RaspAP/raspap-webgui/issues/1512#issuecomment-1925919260

**Closed by billz** 2024-05-09 16:27 UTC
Labels: bug-report, triage
