### ISSUE TITLE
URL rewrites fail

### ISSUE THREAD

**Issue by qaristote** [RaspAP/raspap-webgui#940] opened 2021-06-22 18:24 UTC
## Checklist

- [x] This is a bug report
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Bug description
The lighttpd server does not rewrite URLs according to `50-raspap-config.conf`.

## Your environment
1. Operating System: Raspbian GNU/Linux 10 (buster)
2. Hardware and version: Raspberry Pi 3B+
3. RaspAP version: 2.6.6
5. RaspAP Quick Install or Manual setup? Quick install
6. Using default configuration? Yes
7. Simultaneous AP and managed mode? No
8. Onboard wireless chipset or external adapter? Onboard
9. Other software or services running with RaspAP? No

## Steps to reproduce
Connect to the webgui. Click on any option in the menu, say "Hotspot". I get redirected to https://10.3.141.1/hostapd_conf and get a 404 error. Note that when directly connecting to https://10.3.141.1/index.php/hostapd_conf, the HTML page is loaded but not the CSS code.

## Additional context
I tried changing browsers. 
`sudo lighttpd-enable-mod fastcgi-php` tells me that the module is already enabled.
I did not change the lighttpd configuration files, but note that `lighttpd.conf` does contain the line
```
include "/etc/lighttpd/conf-enabled/*.conf"
```
that `50-raspap-config.conf` does appear in `/etc/lighttpd/conf-enabled/` and does contain 
```
server.modules += (
	"mod_rewrite",
)

$HTTP["url"] =~ "^/var/www/html/(?!(dist|app|ajax|config)).*" {
    url.rewrite-once = ( "^/var/www/html/(.*?)(\?.+)?$"=>"/var/www/html/index.php/$1$2" )
    server.error-handler-404 = "/var/www/html/index.php"
}
```

The only messages I'm getting in `/var/log/lighttpd/error.log` are 

```
(mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  Use of undefined constant RASPI_DNSMASQ_PREFIX - assumed 'RASPI_DNSMASQ_PREFIX' (this will throw an Error in a future version of PHP) in /var/www/html/includes/defaults.php on line 20
(mod_fastcgi.c.421) FastCGI-stderr: PHP Warning:  parse_ini_file(/etc/raspap/hostapd.ini): failed to open stream: No such file or directory in ...
(mod_fastcgi.c.421) FastCGI-stderr: PHP Notice:  Undefined variable: arrHostapdConf in /var/www/html/templates/dashboard.php on line 96
```
which get logged when connecting to the webgui.

**Comment by billz** [comment] 2021-06-22 18:46
Duplicate of #803

**Closed by billz** 2021-06-22 18:46 UTC
Labels: duplicate
