### ISSUE TITLE
Installing telnetd hangs in "sudo apt install telnetd"

### ISSUE THREAD

**Issue by 2bholland** [RaspAP/raspap-webgui#1351] opened 2023-06-01 21:32 UTC
## Checklist

- [x] This is a bug report
- [x] I observed this bug on a clean install of the OS
- [x] I have followed the project prerequisites
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Your environment
1. Operating System: **ENTER HERE** 
2. Hardware and version: 
3. RaspAP version: 
4. Clean install of a compatible operating system? 
5. RaspAP Quick Install or Manual setup? 
6. Using default configuration? 
7. Simultaneous AP and managed mode? 
8. Onboard wireless chipset or external adapter? 
9. Other software or services running with RaspAP?

**Comment by billz** [comment] 2023-06-02 05:06
Duplicate of #1352

**Closed by billz** 2023-06-02 05:06 UTC
