### ISSUE TITLE
Can't connect to a Guest WiFi Network that is not password protected

### ISSUE THREAD

**Issue by knowlesee73** [RaspAP/raspap-webgui#1004] opened 2021-09-14 01:40 UTC
## Checklist

- [x] This is a bug report
- [x] I have searched this repository for existing issues
- [x] I checked the FAQ and official documentation before creating this issue
- [x] I have read and understand the issue reporting guidelines 

## Your environment
1. Operating System: **RPi-OS 32** 
2. Hardware and version: RPi 4
3. RaspAP version: 2.6.6
4. Followed the project prerequisites? Yes
5. RaspAP Quick Install or Manual setup? Quick Install
6. Using default configuration? Yes
7. Simultaneous AP and managed mode? Not Sure
8. Onboard wireless chipset or external adapter? EASTECH Ralink RT5370
9. Other software or services running with RaspAP? OpenVpn

## Steps to reproduce
go to wifi client and try to pick a WiFi network that is not password protected

## Additional context

In WiFi Client in Rapsap GUI, I can see the open network amongst others that are available, but I cannot add it to be connected unless I put something into the passphrase field. I've tried just spaces, 12345, password, anything default enough to hit the connection, but none of it works. Is there a way to connect it?

**Comment by billz** [comment] 2021-09-14 05:52
Duplicate of https://github.com/RaspAP/raspap-webgui/discussions/1006

**Closed by billz** 2021-09-14 05:52 UTC
Labels: duplicate
